@extends('admin.layouts.app')
@section('title', $role->exists ? 'Edit Role' : 'Create Role')
@section('page_title', $role->exists ? 'Edit Role' : 'Create Role')
@section('content')
<div class="mx-auto max-w-6xl space-y-5"><a href="{{ route('admin.system.roles.index') }}" class="text-sm font-semibold text-blue-600">← Roles & Permissions</a>@include('admin.staff._messages')
@if ($role->exists)<p class="rounded-lg bg-amber-50 p-4 text-sm text-amber-800">Changes apply to {{ $role->users_count }} assigned staff on their next request.</p>@endif
<form method="POST" action="{{ $role->exists ? route('admin.system.roles.update', $role) : route('admin.system.roles.store') }}" class="space-y-5" data-permission-matrix>@csrf @if ($role->exists) @method('PUT')<input type="hidden" name="version" value="{{ old('version', $role->version) }}">@endif
<div class="grid gap-4 rounded-xl bg-white p-5 ring-1 ring-slate-200 sm:grid-cols-2"><label class="text-sm font-semibold">Role name<input required name="name" maxlength="100" value="{{ old('name', $role->name) }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm font-semibold">Description<input name="description" maxlength="500" value="{{ old('description', $role->description) }}" class="mt-1 w-full rounded-lg border-slate-300"></label></div>
<div class="overflow-x-auto rounded-xl bg-white ring-1 ring-slate-200"><table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="p-4">Menu</th><th class="p-4">Show Menu / View</th><th class="p-4">Allowed actions</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach ($modules as $key => $module)<tr data-permission-row><td class="p-4 font-semibold">{{ $module['label'] }}</td><td class="p-4"><label class="inline-flex items-center gap-2"><input type="checkbox" name="permissions[]" value="{{ $key }}.view" data-view-permission @checked(in_array($key.'.view', old('permissions', $role->permissions))) class="rounded border-slate-300 text-blue-600">Show / View</label></td><td class="p-4"><div class="flex flex-wrap gap-x-5 gap-y-3">@forelse ($module['actions'] as $action => $label)<label class="inline-flex items-center gap-2"><input type="checkbox" name="permissions[]" value="{{ $key }}.{{ $action }}" data-action-permission @checked(in_array($key.'.'.$action, old('permissions', $role->permissions))) class="rounded border-slate-300 text-blue-600">{{ $label }}</label>@empty<span class="text-slate-400">View only</span>@endforelse</div></td></tr>@endforeach</tbody></table></div>
<p class="text-sm text-slate-500">Hidden menus also block direct URLs and all actions in that module. Only Superadmin can appoint staff or manage roles.</p><button class="rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white">Save Role</button></form>
@if ($role->exists && $role->users_count === 0)<details class="rounded-xl border border-red-200 bg-white p-4"><summary class="cursor-pointer text-sm font-semibold text-red-700">Delete unused role</summary><form method="POST" action="{{ route('admin.system.roles.destroy', $role) }}" class="mt-3">@csrf @method('DELETE')<p class="mb-3 text-sm">This unused role will be removed. Its audit history will be retained.</p><button class="rounded-lg bg-red-600 px-4 py-2 text-sm font-semibold text-white">Confirm Delete Role</button></form></details>@endif
</div>
@endsection
