@extends('admin.layouts.app')
@section('title', $staff->exists ? 'Edit Staff' : 'Add Staff')
@section('page_title', $staff->exists ? 'Edit Staff' : 'Add Staff')
@section('content')
<div class="mx-auto max-w-5xl space-y-5">
    <a href="{{ route('admin.system.staff.index') }}" class="text-sm font-semibold text-blue-600">← User Management</a>
    @include('admin.staff._messages')
    @if ($roles->isEmpty())<p class="rounded-lg bg-amber-50 p-4 text-sm">Create a role first in <a class="font-semibold text-blue-600" href="{{ route('admin.system.roles.create') }}">Roles & Permissions</a>.</p>@endif
    <form method="POST" action="{{ $staff->exists ? route('admin.system.staff.update', $staff) : route('admin.system.staff.store') }}" class="space-y-5" data-staff-access>
        @csrf @if ($staff->exists) @method('PUT') <input type="hidden" name="version" value="{{ old('version', $staff->access_version) }}"> @endif
        <div class="grid gap-4 rounded-xl bg-white p-5 ring-1 ring-slate-200 sm:grid-cols-2">@foreach (['name' => 'Name', 'email' => 'Email', 'phone' => 'Phone number'] as $field => $label)<label class="text-sm font-semibold">{{ $label }}<input name="{{ $field }}" type="{{ $field === 'email' ? 'email' : 'text' }}" value="{{ old($field, $staff->$field) }}" @required($field !== 'phone') maxlength="{{ $field === 'phone' ? 50 : 255 }}" class="mt-1 w-full rounded-lg border-slate-300"></label>@endforeach<label class="text-sm font-semibold">Status<select name="status" class="mt-1 w-full rounded-lg border-slate-300">@foreach (['active' => 'Active', 'inactive' => 'Inactive'] as $value => $label)<option value="{{ $value }}" @selected(old('status', $staff->status) === $value)>{{ $label }}</option>@endforeach</select></label></div>
        <section class="rounded-xl bg-white p-5 ring-1 ring-slate-200"><h2 class="font-semibold">Roles</h2><p class="mt-1 text-sm text-slate-500">Select one or more roles. Access from every selected role is combined.</p><div class="mt-4 grid gap-3 sm:grid-cols-2">@foreach ($roles as $role)<label class="flex items-start gap-3 rounded-lg border border-slate-200 p-3"><input type="checkbox" name="roles[]" value="{{ $role->id }}" data-role-permissions="{{ json_encode($role->permissions) }}" @checked(in_array($role->id, old('roles', $staff->exists ? $staff->accessRoles->modelKeys() : []))) class="mt-1 rounded border-slate-300 text-blue-600"><span><strong class="text-sm">{{ $role->name }}</strong><span class="block text-xs text-slate-500">{{ $role->description }}</span></span></label>@endforeach</div></section>
        <section class="rounded-xl bg-white p-5 ring-1 ring-slate-200"><h2 class="font-semibold">Effective Access</h2><p class="mt-1 text-sm text-slate-500">Preview of the selected roles. Inactive accounts cannot access the platform. Profile and Logout remain available to active staff.</p><div class="mt-4 divide-y divide-slate-100">@foreach ($modules as $key => $module)<div class="flex flex-wrap justify-between gap-2 py-3 text-sm" data-effective-module="{{ $key }}" data-action-labels="{{ json_encode($module['actions']) }}"><span class="font-semibold">{{ $module['label'] }}</span><span data-effective-label class="text-slate-500">Hidden / No Access</span></div>@endforeach</div><noscript><p class="mt-3 text-sm">Enable JavaScript for the live access preview. Permissions are still enforced when saved.</p></noscript></section>
        <p class="text-sm text-slate-500">New staff receive a password invitation. Changing an email address requires a new invitation.</p>
        <button @disabled($roles->isEmpty()) class="rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white disabled:opacity-40">Save Staff</button>
    </form>
    @if ($staff->exists && $staff->invitationPending() && $staff->status === 'active')<form method="POST" action="{{ route('admin.system.staff.invitation', $staff) }}">@csrf<button class="rounded-lg border border-blue-200 px-4 py-2 text-sm font-semibold text-blue-700">Resend Invitation</button></form>@endif
</div>
@endsection
