@extends('admin.layouts.app')
@section('title', 'User Management')
@section('page_title', 'User Management')
@section('content')
<div class="space-y-5">
    <div class="flex flex-wrap items-center justify-between gap-3"><p class="text-sm text-slate-500">Manage staff accounts and the roles that control their access.</p><a href="{{ route('admin.system.staff.create') }}" class="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">Add Staff</a></div>
    @include('admin.staff._messages')
    <form method="GET" class="flex flex-wrap gap-3 rounded-xl bg-white p-4 ring-1 ring-slate-200"><input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Search name or email" aria-label="Search staff" class="rounded-lg border-slate-300"><select name="role_id" aria-label="Filter role" class="rounded-lg border-slate-300"><option value="">All roles</option>@foreach ($roles as $role)<option value="{{ $role->id }}" @selected(($filters['role_id'] ?? '') == $role->id)>{{ $role->name }}</option>@endforeach</select><select name="status" aria-label="Filter status" class="rounded-lg border-slate-300"><option value="">All statuses</option>@foreach (['active' => 'Active', 'inactive' => 'Inactive'] as $value => $label)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2 text-white">Search</button></form>
    <div class="overflow-x-auto rounded-xl bg-white ring-1 ring-slate-200"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="p-4">Staff</th><th class="p-4">Roles</th><th class="p-4">Status</th><th class="p-4">Action</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($staff as $person)<tr class="hover:bg-blue-50"><td class="p-4"><p class="font-semibold">{{ $person->name }}</p><p class="text-slate-500">{{ $person->email }}</p><p class="text-slate-500">{{ $person->phone ?: '—' }}</p></td><td class="p-4">@if ($person->isSuperAdmin())<span class="font-semibold text-purple-700">Superadmin</span>@else{{ $person->accessRoles->pluck('name')->join(', ') ?: 'No roles' }}@endif</td><td class="p-4"><p>{{ ucfirst($person->status) }}</p>@if ($person->invitationPending())<span class="text-xs text-amber-700">Invitation pending</span>@endif</td><td class="p-4">@if (!$person->isSuperAdmin())<a href="{{ route('admin.system.staff.edit', $person) }}" class="font-semibold text-blue-600">View / Edit</a>@else<span class="text-xs text-slate-500">Protected account</span>@endif</td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-slate-500">No matching staff.</td></tr>@endforelse</tbody></table></div>{{ $staff->links() }}
</div>
@endsection
