@extends('admin.layouts.app')
@section('title', $businessSite->site_name.' | Business Site')
@section('page_title', 'Business Site Details')
@section('content')
<div class="space-y-6">
    @error('business_site')<div class="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ $message }}</div>@enderror
    <div class="flex flex-wrap items-start justify-between gap-4"><div><a href="{{ route('admin.business-sites.index') }}" class="text-sm font-semibold text-[#1a73e8]">← Back to business sites</a><h2 class="mt-3 text-2xl font-semibold text-slate-950">{{ $businessSite->site_name }}</h2><p class="mt-1 text-sm text-slate-500">{{ $businessSite->city }}</p></div><a href="{{ route('admin.business-sites.edit', $businessSite) }}" class="rounded-lg bg-[#1a73e8] px-4 py-2.5 text-sm font-semibold text-white">Edit site</a></div>
    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <article class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200/70"><p class="text-xs font-semibold uppercase text-slate-500">Status</p><p class="mt-2 text-xl font-semibold {{ $businessSite->isOpen() ? 'text-emerald-700' : 'text-slate-800' }}">{{ $businessSite->isOpen() ? 'Open' : 'Closed' }}</p></article>
        <article class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200/70"><p class="text-xs font-semibold uppercase text-slate-500">Assigned agents</p><p class="mt-2 text-xl font-semibold text-slate-900">{{ $businessSite->agents_count }}</p></article>
        <article class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200/70"><p class="text-xs font-semibold uppercase text-slate-500">POS sales</p><p class="mt-2 text-xl font-semibold text-slate-900">{{ $businessSite->pos_sales_count }}</p></article>
        <article class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200/70"><p class="text-xs font-semibold uppercase text-slate-500">Operation records</p><p class="mt-2 text-xl font-semibold text-slate-900">{{ $businessSite->operations_count }}</p></article>
    </section>
    <section class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200/70"><div class="border-b border-slate-200 px-5 py-4"><h3 class="font-semibold text-slate-950">Assigned agents</h3></div><div class="divide-y divide-slate-100">@forelse ($businessSite->agents as $agent)<div class="flex flex-wrap items-center justify-between gap-3 px-5 py-4"><div><p class="font-semibold text-slate-900">{{ $agent->agt_name }}</p><p class="mt-0.5 font-mono text-xs text-slate-500">{{ $agent->login_id }}</p></div><p class="text-sm text-slate-500">{{ $agent->email }}</p></div>@empty<p class="px-5 py-10 text-center text-sm text-slate-500">No agents assigned.</p>@endforelse</div></section>
    <section class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200/70"><div class="border-b border-slate-200 px-5 py-4"><h3 class="font-semibold text-slate-950">Recent operations</h3></div><div class="divide-y divide-slate-100">@forelse ($recentOperations as $operation)<a href="{{ route('admin.business-site-operations.show', $operation) }}" class="flex flex-wrap items-center justify-between gap-3 px-5 py-4 transition hover:bg-slate-50"><div><p class="font-semibold text-slate-900">{{ $operation->opened_at->format('d M Y, h:i A') }}</p><p class="mt-0.5 text-xs text-slate-500">{{ $operation->closed_at?->format('d M Y, h:i A') ?? 'Open now' }}</p></div><span class="text-sm font-semibold text-[#1a73e8]">Details →</span></a>@empty<p class="px-5 py-10 text-center text-sm text-slate-500">No operation records yet.</p>@endforelse</div></section>
    <section class="rounded-xl border border-red-200 bg-red-50 p-5"><h3 class="font-semibold text-red-800">Delete business site</h3><p class="mt-1 text-sm text-red-700">A site with sales or operation history cannot be deleted.</p><form method="POST" action="{{ route('admin.business-sites.destroy', $businessSite) }}" class="mt-4" onsubmit="return confirm('Delete this business site?')">@csrf @method('DELETE')<button type="submit" class="rounded-lg border border-red-300 bg-white px-4 py-2.5 text-sm font-semibold text-red-700">Delete site</button></form></section>
</div>
@endsection
