@extends('admin.layouts.app')
@section('title','Customer Order')
@section('content')
<div class="space-y-5"><a href="{{ route('admin.customer-orders.index') }}">← Customer Orders</a><div class="flex flex-wrap items-center justify-between gap-3"><h1 class="text-xl font-bold">{{ $order->order_number }} · Katalog Pelanggan</h1>
@if($order->customerWhatsAppUrl())
<a href="{{ $order->customerWhatsAppUrl() }}" target="_blank" rel="noopener noreferrer" class="inline-flex min-h-11 items-center rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-800">WhatsApp Pelanggan</a>
@else
<span class="text-sm text-slate-500">Nombor WhatsApp pelanggan tidak tersedia.</span>
@endif
</div><p class="text-sm text-slate-500">WhatsApp menggunakan status terakhir yang disimpan. Semak mesej sebelum menghantar.</p>
@if($order->customer_received_at)<p class="rounded-lg bg-emerald-50 p-3 font-bold text-emerald-900">Penerimaan disahkan pelanggan · {{ $order->customer_received_at->format('d/m/Y H:i') }} · Pautan pelanggan tamat.</p>@endif
@if(session('success'))<p class="text-green-700">{{ session('success') }}</p>@endif @if($errors->any())<p class="text-red-700">{{ $errors->first() }}</p>@endif
<section class="rounded-xl border bg-white p-4"><p>Ejen perujuk: <strong>{{ $order->agent->agt_name }}</strong> ({{ $order->agent->login_id }})</p><p>Pelanggan: {{ $order->recipient_name }} · {{ $order->phone_number }}</p><p>{{ $order->delivery_address }}</p><p>{{ $order->notes }}</p><p>{{ $order->statusLabel() }} · {{ $order->paymentStatusLabel() }}</p><p>Produk RM {{ $order->subtotal }} + penghantaran RM {{ number_format($order->deliveryFeeAmount(),2) }} = RM {{ $order->total_amount }}</p>
@foreach($order->items as $item)<p class="mt-2">{{ $item->product_name }} · {{ $item->clickerCharactersText() }} · {{ $item->quantity }} × RM {{ $item->unit_price }}</p>@endforeach
@foreach($order->paymentProofPaths() as $path)<a class="mr-4 underline" target="_blank" href="{{ route('admin.customer-orders.proof',[$order,$loop->index]) }}">Bukti bayaran {{ $loop->iteration }}</a>@endforeach</section>
@if(\App\Support\AdminAccess::allows(auth('admin')->user(),'customer-orders.edit'))
<form method="post" action="{{ route('admin.customer-orders.update',$order) }}" class="grid gap-3 rounded-xl border bg-white p-4">@csrf @method('PUT')<h2 class="font-bold">Urus pesanan</h2><select name="action" class="rounded border p-2"><option value="instructions">Arahan pembayaran</option><option value="payment">Status bayaran</option><option value="process">Process</option><option value="ready">Siap</option><option value="ship">Dihantar</option><option value="pickup_ready">Sedia Diambil</option><option value="complete">Selesai</option><option value="request_proof">Minta bukti bayaran baharu</option><option value="cancel">Cancel</option><option value="refund">Pelarasan nilai produk dipulangkan</option></select><label>Kurier<input name="courier" value="{{ $order->courier }}" class="block w-full rounded border p-2"></label><label>Nombor tracking<input name="tracking_number" value="{{ $order->tracking_number }}" class="block w-full rounded border p-2"></label><label>Arahan pembayaran<textarea name="payment_instructions" class="block w-full rounded border p-2">{{ $order->payment_instructions }}</textarea></label><label>Status bayaran<select name="payment_status" class="block rounded border p-2">@foreach(['unpaid','paid','refunded'] as $status)<option @selected($order->payment_status===$status)>{{ $status }}</option>@endforeach</select></label><label>Nilai produk dipulangkan, jumlah kumulatif (RM)<input type="number" step="0.01" min="0" max="{{ $order->subtotal }}" name="refunded_product_amount" value="{{ $order->refunded_product_amount }}" class="block rounded border p-2"></label><p class="text-sm">Pelarasan pulangan ini mengubah komisen sahaja. Ia tidak menambah stok secara automatik.</p><input name="reason" required placeholder="Sebab perubahan (wajib)" class="rounded border p-2"><button class="rounded bg-blue-700 p-3 text-white">Simpan perubahan</button></form>
@endif
<section class="space-y-3 rounded-xl border bg-white p-4"><h2 class="font-bold">Komisen {{ $order->commission_rate }}%</h2><p>Anggaran asal RM {{ $order->commission_amount }} · Semasa RM {{ number_format($order->earnedCommissionCents()/100,2) }} · {{ $order->commissionStatus() }}</p><p>Diselesaikan RM {{ number_format($order->paidCommissionCents()/100,2) }}</p>
@if($order->commissionStatus()==='Eligible' && \App\Support\AdminAccess::allows(auth('admin')->user(),'customer-orders.commission'))

<p class="font-bold">Bayaran tunai selepas pelarasan terdahulu: RM {{ number_format(max(0,$due-$debt)/100,2) }}</p>
<form method="post" enctype="multipart/form-data" action="{{ route('admin.customer-orders.payout',$order) }}" class="grid gap-3">@csrf<input type="hidden" name="expected_amount" value="{{ $due/100 }}"><input type="hidden" name="expected_cash" value="{{ max(0,$due-$debt)/100 }}"><label>Bukti bayaran komisen (maksimum 5 MB)<input type="file" name="proof" accept=".jpg,.jpeg,.png,.webp,.pdf" @required($due>$debt)></label><input required name="reference" placeholder="Rujukan transaksi bayaran" class="rounded border p-2"><input required name="reason" placeholder="Catatan bayaran" class="rounded border p-2"><button class="rounded bg-emerald-700 p-3 text-white">Rekod bayaran komisen</button></form>@endif
@foreach($entries as $entry)<p class="border-t pt-2 text-sm">{{ $entry->created_at }} · Admin #{{ $entry->admin_id }} · {{ $entry->type }} · RM {{ $entry->amount }} · {{ $entry->reference }} · {{ $entry->reason }} @if($entry->proof_path)<a class="underline" href="{{ route('admin.customer-orders.commission-proof',[$order,$entry->id]) }}" target="_blank">Bukti bayaran</a>@endif @if($entry->cash_amount !== null) · Tunai RM {{ $entry->cash_amount }} @endif</p>@endforeach</section></div>
@endsection
